language: python
python:
  - 3.5
  - 3.6

#these directories are persistent
cache: pip

before_install:
  - pip install coverage coveralls
script:
  - "coverage run --source=qupulse --rcfile=coverage.ini setup.py test"
after_success:
  - coveralls

notifications:
  email: false
